import json
from typing import Any

from app.core.config import get_settings


def generate_query(question: str, schema: dict[str, Any], engine: str = "sql") -> dict[str, Any]:
    settings = get_settings()
    if settings.openai_api_key:
        return _openai_ready_stub(question, schema, engine)
    return _mock_query(question, schema, engine)


def _openai_ready_stub(question: str, schema: dict[str, Any], engine: str) -> dict[str, Any]:
    settings = get_settings()
    if settings.app_env in {"local", "test"}:
        return _mock_query(question, schema, engine, provider="openai-configured")
    try:
        from openai import OpenAI

        client = OpenAI(api_key=settings.openai_api_key)
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            temperature=0,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are InsightAI's safe query generation agent. Return only JSON with keys "
                        "engine, query, explanation, chart_type. SQL must be read-only SELECT. "
                        "MongoDB must be an aggregation pipeline array with read-only stages."
                    ),
                },
                {"role": "user", "content": json.dumps({"question": question, "schema": schema, "engine": engine})},
            ],
        )
        content = response.choices[0].message.content or "{}"
        parsed = json.loads(content)
        return {
            "provider": "openai",
            "engine": parsed.get("engine", engine),
            "query": parsed.get("query", ""),
            "explanation": parsed.get("explanation", "Generated by OpenAI query agent."),
            "chart_type": parsed.get("chart_type", "table"),
        }
    except Exception:
        return _mock_query(question, schema, engine, provider="openai-fallback")


def _mock_query(question: str, schema: dict[str, Any], engine: str, provider: str = "mock") -> dict[str, Any]:
    q = question.lower()
    if len(q.split()) < 3 or any(term in q for term in ["something", "stuff", "anything"]):
        return {
            "provider": provider,
            "engine": engine,
            "query": "",
            "clarification_required": True,
            "explanation": "Please clarify the metric, dimension, and time period you want to analyze.",
            "chart_type": "table",
        }
    if engine == "mongodb" or "mongodb" in q or "aggregation" in q:
        return {
            "provider": provider,
            "engine": "mongodb",
            "query": [
                {"$match": {"event": {"$in": ["login", "purchase", "subscription"]}}},
                {"$group": {"_id": "$customer", "activity": {"$sum": "$value"}}},
                {"$sort": {"activity": -1}},
                {"$limit": 10},
            ],
            "explanation": "Groups customer activity events by customer and ranks accounts by activity value.",
        }
    if "region" in q or "compare" in q:
        sql = "SELECT region, SUM(revenue) AS revenue, SUM(units) AS units FROM sales GROUP BY region ORDER BY revenue DESC"
        chart = "bar"
    elif "customer" in q or "top 10" in q:
        sql = "SELECT customer, SUM(revenue) AS revenue FROM sales GROUP BY customer ORDER BY revenue DESC"
        chart = "bar"
    elif "inventory" in q:
        sql = "SELECT product, warehouse, region, on_hand, reorder_point FROM inventory ORDER BY on_hand ASC"
        chart = "bar"
    elif "expense" in q or "cost" in q:
        sql = "SELECT expense_month, region, SUM(expense_amount) AS expenses FROM expenses GROUP BY expense_month, region ORDER BY expense_month"
        chart = "bar"
    elif "order" in q:
        sql = "SELECT region, status, COUNT(*) AS orders, SUM(order_value) AS order_value FROM orders GROUP BY region, status ORDER BY order_value DESC"
        chart = "bar"
    elif "employee" in q:
        sql = "SELECT region, COUNT(*) AS employees, SUM(quota) AS quota FROM employees GROUP BY region ORDER BY quota DESC"
        chart = "bar"
    elif "product" in q or "low sales" in q:
        sql = "SELECT product, SUM(revenue) AS revenue, SUM(units) AS units FROM sales GROUP BY product ORDER BY revenue ASC"
        chart = "table"
    elif "growth" in q or "trend" in q or "month" in q or "revenue" in q:
        sql = "SELECT order_month, SUM(revenue) AS revenue, SUM(units) AS units FROM sales GROUP BY order_month ORDER BY order_month"
        chart = "line"
    else:
        sql = "SELECT order_month, region, customer, product, revenue, units FROM sales ORDER BY order_month DESC"
        chart = "table"
    return {
        "provider": provider,
        "engine": "sql",
        "query": sql,
        "explanation": "Uses the selected analytics schema, aggregates requested business metrics, and keeps execution read-only.",
        "chart_type": chart,
    }


def generate_insights(rows: list[dict[str, Any]], question: str) -> dict[str, Any]:
    if not rows:
        return {
            "summary": "No rows were returned for this request.",
            "trends": [],
            "anomalies": [],
            "recommendations": ["Try broadening the date range or selecting a different table."],
        }
    numeric_keys = [key for key, value in rows[0].items() if isinstance(value, (int, float))]
    largest = None
    if numeric_keys:
        key = numeric_keys[0]
        largest = max(rows, key=lambda row: float(row.get(key) or 0))
    return {
        "summary": f"InsightAI analyzed {len(rows)} result rows for: {question}",
        "trends": ["Revenue concentration is visible across the leading categories.", "Recent periods show stronger performance in the top segment."],
        "anomalies": ["One segment appears below trend and should be reviewed for pipeline or retention issues."],
        "recommendations": ["Save this view to an executive dashboard.", "Compare this result against margin and customer segment."],
        "highlight": largest,
    }


def recommend_chart(rows: list[dict[str, Any]], preferred: str = "table") -> dict[str, Any]:
    if not rows:
        return {"type": "table", "x": None, "y": None}
    keys = list(rows[0].keys())
    numeric = [k for k in keys if isinstance(rows[0].get(k), (int, float))]
    categorical = [k for k in keys if k not in numeric]
    lower_keys = {key.lower() for key in keys}
    if len(rows) == 1 and numeric:
        return {"type": "kpi", "columns": keys}
    if {"region", "country"} & lower_keys:
        return {"type": "map", "x": "region" if "region" in lower_keys else "country", "y": numeric[0] if numeric else None}
    if any("share" in key.lower() or "percent" in key.lower() for key in keys) and categorical and numeric:
        return {"type": "donut", "x": categorical[0], "y": numeric[0]}
    if preferred == "line" and categorical and numeric:
        return {"type": "line", "x": categorical[0], "y": numeric[0]}
    if preferred in {"bar", "area", "pie"} and categorical and numeric:
        return {"type": preferred, "x": categorical[0], "y": numeric[0]}
    return {"type": "table", "columns": keys}
