"""initial InsightAI schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-27
"""

from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Models are created during local startup for developer speed. Production
    # teams can replace this baseline with an autogenerated migration.
    pass


def downgrade() -> None:
    pass
